CREATE TABLE Crop (
'CropId' INT NOT NULL AUTO_INCREMENT,
'Crop' VARCHAR(64) NOT NULL,
'Variety' VARCHAR(64) NOT NULL,

PRIMARY KEY ('CropId')
);


CREATE TABLE Bed (
'BedId' INT NOT NULL AUTO_INCREMENT,
'Location' VARCHAR(128) NOT NULL,
'Description' VARCHAR(128),
'Label' VARCHAR(128),
'Type' VARCHAR(64),
'Size' VARCHAR(64),

PRIMARY KEY ('BedId'),

);

CREATE TABLE BedStatus (
'Id' INT NOT NULL AUTO_INCREMENT,
'BedID' VARCHAR(128) NOT NULL,
'Status' VARCHAR(128),
'Timestamp' DATETIME,
PRIMARY KEY ('Id'),
FOREIGN KEY ('BedID') References Bed(BedId)
);

CREATE TABLE SensorLogging (
'Id' INT NOT NULL AUTO_INCREMENT,
'BedID' VARCHAR(128) NOT NULL,
'Location' VARCHAR(128),
'Sensor' VARCHAR(128) NOT NULL,
'Value' INT NOT NULL,
'Timestamp' DATETIME,
PRIMARY KEY ('Id'),
FOREIGN KEY ('BedID') References Bed(BedId)
);

CREATE TABLE Harvest (
'Id' INT NOT NULL AUTO_INCREMENT,
'BedID' VARCHAR(128) NOT NULL,
'CropID' VARCHAR(128) NOT NULL,
'Quantity' INT,
'Timestamp' DATETIME,
PRIMARY KEY ('Id'),
FOREIGN KEY ('BedID') References Bed(BedId)
);
